-- ⚠️ 本迁移是**有意的空操作**，不要往里加 SQL。
--
-- 原计划：给 `KnowledgeChunk`.`text` 加 ngram FULLTEXT 索引，为 P1 混合检索
-- 提供「词面」召回（与块级向量一路进 RRF 融合，应用侧见 src/lib/llm/keyword-retrieval.ts）。
--
-- 为什么放弃（2026-09-17 决策）：
--   生产库是 **MariaDB 10.5**，不支持 MySQL 专有的 `WITH PARSER ngram`。
--   首次发布时本迁移在生产上以 P3018 / errno 1128
--   （`Function 'ngram' is not defined`）失败。CI 用 MySQL 8.4，所以这个差异
--   在合并前没被任何门禁暴露出来。
--
--   为什么**不**退而求其次建「默认解析器」的 FULLTEXT 索引：
--   MySQL/MariaDB 内置解析器按空格与标点切词，中文没有词边界，整段文本会落成
--   一个 token。索引建得出来、`MATCH ... AGAINST` 也不报错，只是中文召回极差 ——
--   这是比「没有索引」更坏的失败模式：一个静默的、看起来在工作、实际不工作的检索路。
--   宁可明确停用，不要静默劣化。
--
-- 现状（无需人工干预）：
--   `keyword-retrieval.ts` 在检索前探测 `KnowledgeChunk.text` 上是否存在可用的
--   FULLTEXT 索引，探测不通过就直接短路，**不查库、不刷日志**。
--   混合检索因此在当前生产上固定等价为纯向量召回。
--   融合层的归一化本来就是按「单路有结果」这一档设计的，排序稳定性不受影响
--   （见 rank-fusion.ts 的 FUSION_SCORE_FLOOR 说明）。
--
-- 保留这个空迁移而不是删除它的原因：
--   这条迁移在生产 `_prisma_migrations` 里已有一条**失败**记录。
--   删掉文件会让本地历史与库里的记录对不上；保留文件 + 在服务器上执行一次
--   `prisma migrate resolve --applied 20260916160000_add_knowledge_chunk_fulltext`
--   即可把失败标记收敛为「已应用」，且后续部署不再被它阻塞。
--
-- 什么时候需要恢复词面召回：
--   1. 数据库换成 MySQL 8（或 MariaDB 启用 Mroonga / 外部检索引擎）；
--   2. 库上手工建索引（schema 里刻意不声明 `@@fulltext`，见 knowledge.prisma 的说明）：
--        ALTER TABLE `KnowledgeChunk`
--          ADD FULLTEXT INDEX `KnowledgeChunk_text_idx` (`text`) WITH PARSER ngram;
--      建好后**无需改代码**：下一次检索探测到索引即可自动启用词面路。
--      核实：SHOW INDEX FROM `KnowledgeChunk` WHERE Key_name = 'KnowledgeChunk_text_idx';
--      应看到 Index_type = FULLTEXT。
--   3. 或者改用不依赖数据库全文特性的方案（应用侧倒排 / bigram 打分表），
--      那样连上面这条 ALTER 都不需要。
--
-- 回滚：本迁移无 DDL，无需回滚。

-- 故意留空：不要在下面添加任何语句。
