"use client"

// Compatibility barrel: domain APIs live beside this file.
export * from "./core"
export * from "./auth"
export * from "./hot"
export * from "./content"
export * from "./media"
export * from "./topics"
export * from "./competitor"
export * from "./knowledge"
export * from "./aim"
export * from "./projects"
export * from "./aim-chat"
export * from "./inspiration"
