CREATE TABLE IF NOT EXISTS `AuditEvent` (
    `id` VARCHAR(191) NOT NULL,
    `occurredAt` DATETIME(3) NOT NULL,
    `ingestedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `source` VARCHAR(32) NOT NULL,
    `category` VARCHAR(32) NOT NULL,
    `severity` VARCHAR(16) NOT NULL,
    `status` VARCHAR(16) NOT NULL,
    `action` VARCHAR(120) NOT NULL,
    `summary` TEXT NOT NULL,
    `actorType` VARCHAR(32) NULL,
    `actorIdHash` VARCHAR(32) NULL,
    `targetType` VARCHAR(80) NULL,
    `targetId` VARCHAR(191) NULL,
    `projectId` VARCHAR(191) NULL,
    `environment` VARCHAR(32) NULL,
    `correlationId` VARCHAR(80) NULL,
    `requestId` VARCHAR(80) NULL,
    `traceId` VARCHAR(80) NULL,
    `gitSha` VARCHAR(64) NULL,
    `sourceRecordType` VARCHAR(80) NULL,
    `sourceRecordId` VARCHAR(191) NULL,
    `idempotencyKey` VARCHAR(191) NOT NULL,
    `metadata` JSON NULL,
    `externalLogUrl` TEXT NULL,

    UNIQUE INDEX `AuditEvent_source_idempotencyKey_key`(`source`, `idempotencyKey`),
    INDEX `AuditEvent_occurredAt_idx`(`occurredAt` DESC),
    INDEX `AuditEvent_source_occurredAt_idx`(`source`, `occurredAt` DESC),
    INDEX `AuditEvent_category_occurredAt_idx`(`category`, `occurredAt` DESC),
    INDEX `AuditEvent_severity_occurredAt_idx`(`severity`, `occurredAt` DESC),
    INDEX `AuditEvent_status_occurredAt_idx`(`status`, `occurredAt` DESC),
    INDEX `AuditEvent_correlationId_occurredAt_idx`(`correlationId`, `occurredAt` DESC),
    INDEX `AuditEvent_actorIdHash_occurredAt_idx`(`actorIdHash`, `occurredAt` DESC),
    INDEX `AuditEvent_projectId_occurredAt_idx`(`projectId`, `occurredAt` DESC),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
