CREATE TABLE `PexelsMedia` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `pexelsId` int NOT NULL,
  `mediaType` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `width` int NOT NULL,
  `height` int NOT NULL,
  `url` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `photographer` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `photographerUrl` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `photographerId` int DEFAULT NULL,
  `avgColor` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alt` text COLLATE utf8mb4_unicode_ci,
  `duration` int DEFAULT NULL,
  `srcJson` json DEFAULT NULL,
  `videoFilesJson` json DEFAULT NULL,
  `videoPicturesJson` json DEFAULT NULL,
  `imageUrl` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ossUrl` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ossStatus` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `ossTransferredAt` datetime(3) DEFAULT NULL,
  `discoveryQuery` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `PexelsMedia_pexelsId_key` (`pexelsId`),
  KEY `PexelsMedia_mediaType_createdAt_idx` (`mediaType`, `createdAt`),
  KEY `PexelsMedia_ossStatus_idx` (`ossStatus`),
  KEY `PexelsMedia_discoveryQuery_idx` (`discoveryQuery`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PexelsQueryCache` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `queryHash` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `query` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mediaType` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `orientation` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `size` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `color` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `totalResults` int NOT NULL DEFAULT '0',
  `pexelsIds` json NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `PexelsQueryCache_queryHash_key` (`queryHash`),
  KEY `PexelsQueryCache_query_mediaType_idx` (`query`, `mediaType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
