"use client";

import { useEffect, useRef } from "react";
import { AlertTriangle, Check, ChevronRight, Flame, Loader2, RefreshCw, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import type { ApiTopicCard } from "@/types/api";

const ELEMENT_CODE_COLORS: Record<string, string> = {
  cost: "bg-green-100 text-green-700 border-green-200",
  authority: "bg-violet-100 text-violet-700 border-violet-200",
  curiosity: "bg-sky-100 text-sky-700 border-sky-200",
  trust: "bg-emerald-100 text-emerald-700 border-emerald-200",
  emotion: "bg-rose-100 text-rose-700 border-rose-200",
  identity: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
  novelty: "bg-amber-100 text-amber-700 border-amber-200",
  practical: "bg-blue-100 text-blue-700 border-blue-200",
  social: "bg-orange-100 text-orange-700 border-orange-200",
  scarcity: "bg-pink-100 text-pink-700 border-pink-200",
  story: "bg-indigo-100 text-indigo-700 border-indigo-200",
  contrast: "bg-teal-100 text-teal-700 border-teal-200",
};

const ELEMENT_CODE_NAMES: Record<string, string> = {
  cost: "低成本", authority: "权威背书", curiosity: "好奇驱动",
  trust: "信任铺垫", emotion: "情绪共鸣", identity: "身份认同",
  novelty: "新奇刺激", practical: "实用干货", social: "社交货币",
  scarcity: "稀缺紧迫", story: "故事叙事", contrast: "对比反差",
};

export function getElementBadgeClass(code: string) {
  return ELEMENT_CODE_COLORS[code] ?? "bg-muted text-muted-foreground";
}

export function getElementName(code: string) {
  return ELEMENT_CODE_NAMES[code] ?? code;
}

export function PhaseTopic({
  topicCards,
  topicSelectionId,
  selectedTopicIndex,
  selectedTopicCard,
  topicLoading,
  topicRefreshCount,
  hotTopicTitle,
  ipProfileReady,
  ipProfileLoading,
  onGenerateTopics,
  onSelectTopic,
  onNext,
}: {
  topicCards: ApiTopicCard[];
  topicSelectionId: string | null;
  selectedTopicIndex: number | null;
  selectedTopicCard: ApiTopicCard | null;
  topicLoading: boolean;
  topicRefreshCount: number;
  hotTopicTitle: string | null;
  ipProfileReady: boolean;
  ipProfileLoading: boolean;
  onGenerateTopics: () => void;
  onSelectTopic: (index: number) => void;
  onNext: () => void;
}) {
  // Auto-generate on first mount
  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (ipProfileReady && !hasAutoGenerated.current && topicCards.length === 0 && !topicLoading) {
      hasAutoGenerated.current = true;
      onGenerateTopics();
    }
  }, [ipProfileReady, topicCards.length, topicLoading, onGenerateTopics]);

  return (
    <div className="space-y-4 sm:space-y-6">
      <div>
        <h2 className="text-base sm:text-lg font-semibold flex items-center gap-2">
          <Sparkles className="h-4 w-4 sm:h-5 sm:w-5 text-primary" />
          内容生产官 · 选题输入
        </h2>
        <p className="text-xs sm:text-sm text-muted-foreground mt-0.5 sm:mt-1">
          先确定这条口播要讲什么，后续文案、包装和素材都会围绕这个表达目标展开。
        </p>
      </div>

      {!ipProfileReady && (
        <Card className="border-amber-200 bg-amber-50">
          <CardContent className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-start gap-3">
              {ipProfileLoading ? (
                <Loader2 className="h-4 w-4 animate-spin text-amber-600 mt-0.5 shrink-0" />
              ) : (
                <AlertTriangle className="h-4 w-4 text-amber-600 mt-0.5 shrink-0" />
              )}
              <div>
                <p className="text-sm font-medium text-amber-800">首次进入需要先建立 IP 档案</p>
                <p className="text-xs text-amber-700 mt-0.5">
                  完成 5 个基础问题后，AI 会自动生成商业定位、人设定位、内容定位，确认后才能生成选题。
                </p>
              </div>
            </div>
            <Button
              type="button"
              size="sm"
              className="cursor-pointer shrink-0"
              onClick={() => { window.location.href = "/ip-profile"; }}
            >
              去完成基础问卷
            </Button>
          </CardContent>
        </Card>
      )}

      {/* Hot topic banner from home page */}
      {hotTopicTitle && (
        <Card className="border-orange-200 bg-orange-50">
          <CardContent className="flex items-center gap-3 py-3">
            <Flame className="h-4 w-4 text-orange-500 shrink-0" />
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-orange-800">
                追热点：{hotTopicTitle}
              </p>
              <p className="text-xs text-orange-600 mt-0.5">
                热点话题将融入 AI 文案生成，提升时效性和流量潜力
              </p>
            </div>
            <Badge variant="outline" className="text-orange-600 border-orange-300 shrink-0">
              热点加持
            </Badge>
          </CardContent>
        </Card>
      )}

      {topicLoading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {Array.from({ length: 4 }).map((_, i) => (
            <Card key={i}>
              <CardHeader className="pb-2"><Skeleton className="h-5 w-40" /></CardHeader>
              <CardContent className="space-y-2">
                <div className="flex gap-1"><Skeleton className="h-5 w-16 rounded-full" /><Skeleton className="h-5 w-16 rounded-full" /></div>
                <Skeleton className="h-3 w-full" />
                <Skeleton className="h-3 w-5/6" />
              </CardContent>
            </Card>
          ))}
        </div>
      ) : topicCards.length > 0 ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {topicCards.map((card, index) => {
            const isSelected = selectedTopicIndex === index;
            return (
              <Card
                key={`${topicSelectionId}-${index}`}
                className={`cursor-pointer transition-colors duration-200 hover:border-primary/50 ${
                  isSelected ? "border-primary ring-2 ring-primary/20 bg-primary/[0.02]" : ""
                }`}
                onClick={() => onSelectTopic(index)}
              >
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm sm:text-base leading-tight">{card.title}</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="flex flex-wrap gap-1">
                    {card.elementCodes.map((code) => (
                      <Badge key={code} variant="outline" className={`text-[10px] sm:text-xs ${getElementBadgeClass(code)}`}>
                        {getElementName(code)}
                      </Badge>
                    ))}
                  </div>
                  {card.rationale && (
                    <p className="text-xs text-muted-foreground leading-relaxed">{card.rationale}</p>
                  )}
                  {isSelected && (
                    <div className="flex items-center gap-1 text-primary text-xs font-medium pt-1">
                      <Check className="h-3.5 w-3.5" /> 已选择
                    </div>
                  )}
                </CardContent>
              </Card>
            );
          })}
        </div>
      ) : (
        <Card className="border-dashed">
          <CardContent className="text-sm text-muted-foreground">
            点击下方按钮生成选题方向
          </CardContent>
        </Card>
      )}

      {/* Refresh button */}
      <div className="flex items-center gap-3">
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={onGenerateTopics}
          disabled={topicLoading || !ipProfileReady}
          className="cursor-pointer gap-1.5"
        >
          {topicLoading ? (
            <><Loader2 className="h-3.5 w-3.5 animate-spin" />生成中...</>
          ) : (
            <><RefreshCw className="h-3.5 w-3.5" />换一批</>
          )}
        </Button>
        {topicRefreshCount >= 3 && (
          <span className="text-xs text-muted-foreground">已优化结果</span>
        )}
      </div>

      {/* Spacer for sticky bottom bar */}
      <div className="h-20" />

      {/* Sticky bottom action bar */}
      {selectedTopicCard && topicSelectionId && (
        <div className="sticky bottom-0 z-30 border-t bg-background/95 backdrop-blur-sm p-3 pb-[calc(0.75rem+env(safe-area-inset-bottom,0px))]">
          <div className="flex justify-end max-w-4xl mx-auto">
            <Button type="button" onClick={onNext} className="cursor-pointer">
              下一步：定文案 <ChevronRight className="h-4 w-4 ml-1" />
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
