ALTER TABLE `AimGeneration`
  MODIFY COLUMN `rawInput` MEDIUMTEXT NOT NULL,
  MODIFY COLUMN `videoScript` MEDIUMTEXT NULL,
  MODIFY COLUMN `wechatArticle` MEDIUMTEXT NULL,
  MODIFY COLUMN `momentsPost` MEDIUMTEXT NULL,
  MODIFY COLUMN `communityMessage` MEDIUMTEXT NULL,
  MODIFY COLUMN `shootingBrief` MEDIUMTEXT NULL,
  MODIFY COLUMN `rawCopy` MEDIUMTEXT NULL,
  MODIFY COLUMN `ipSnapshotUsed` MEDIUMTEXT NULL,
  MODIFY COLUMN `polishInstruction` MEDIUMTEXT NULL,
  MODIFY COLUMN `reviewNote` MEDIUMTEXT NULL,
  MODIFY COLUMN `publishUrl` MEDIUMTEXT NULL,
  MODIFY COLUMN `errorMessage` MEDIUMTEXT NULL;
